[default_session]
startup_command = "nvim ."

[[session]]
name = " neovim config"
path = "~/.dotfiles/nvim/.config/nvim"

[[session]]
name = " tmux config"
path = "~/.dotfiles/tmux/.config/tmux"
startup_command = "nvim tmux.conf"
