"$schema" = "https://starship.rs/config-schema.json"

palette = "catppuccin_mocha"
format = """
$os \
$directory\
$git_branch$git_commit$git_state$git_status\
$fill\
$golang$lua$nodejs$python$rust\
$cmd_duration$time
$character
"""

[os]
disabled = false
style = "bold surface3"

[os.symbols]
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bold lavender"

[git_branch]
symbol = " "
style = "bold green"

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[fill]
symbol = " "

[golang]
symbol = " "
format = "via [$symbol($version )]($style)"

[lua]
symbol = " "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[$symbol$pyenv_prefix($version )(\\($virtualenv\\) )]($style)"
style = "bold blue"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"

[time]
disabled = false
style = "bold teal"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
